# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: template.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'template.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etemplate.proto\x12\x03\x63s2\".\n\x07Message\x12\n\n\x02\x66r\x18\x01 \x01(\x03\x12\n\n\x02to\x18\x02 \x01(\x03\x12\x0b\n\x03msg\x18\x03 \x01(\t\"*\n\rFastHandshake\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05\x65rror\x18\x02 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'template_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGE']._serialized_start=23
  _globals['_MESSAGE']._serialized_end=69
  _globals['_FASTHANDSHAKE']._serialized_start=71
  _globals['_FASTHANDSHAKE']._serialized_end=113
# @@protoc_insertion_point(module_scope)
