# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ex3file.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'ex3file.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rex3file.proto\"W\n\tmessaggio\x12\x10\n\x03\x66ro\x18\x01 \x01(\x03H\x00\x88\x01\x01\x12\x0f\n\x02to\x18\x02 \x01(\x03H\x01\x88\x01\x01\x12\x10\n\x03msg\x18\x03 \x01(\tH\x02\x88\x01\x01\x42\x06\n\x04_froB\x05\n\x03_toB\x06\n\x04_msg\"A\n\thandshake\x12\x0f\n\x02id\x18\x01 \x01(\x03H\x00\x88\x01\x01\x12\x12\n\x05\x65rror\x18\x02 \x01(\x08H\x01\x88\x01\x01\x42\x05\n\x03_idB\x08\n\x06_errorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ex3file_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGGIO']._serialized_start=17
  _globals['_MESSAGGIO']._serialized_end=104
  _globals['_HANDSHAKE']._serialized_start=106
  _globals['_HANDSHAKE']._serialized_end=171
# @@protoc_insertion_point(module_scope)
